config/routes.rb
Rails.application.routes.draw do

root :to => "cocktails#index"


get 'cocktails/map'
get 'pages/map'
get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

resources :users

resources :cocktails do
  resources :comments
end

delete 'cocktails/:id', to: "cocktails#delete", as: :delete_cocktail
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  #tell geocoder where to look to get the human-readable address string, which it will use to work out the lat/long coordinates
  geocoded_by :address
  after_validation :geocode

  belongs_to :user, optional: true
  has_many :comments
  #tell geocoder to actually turn the above address into a latitude and longitude(by doing a lookup in a remote API) any time you create or update a Cocktail item
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cocktail, optional: true
end

app/models/user.rb
class User < ApplicationRecord

    has_many :cocktails
    



    has_secure_password

# Specify that the email field must be present when creating a user...
# ... and also unique!
validates :email, presence: true, uniqueness: true

validates :name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Run the fetch_user method (which sets @current_user)
  # before running the code in every method of every controller
  before_action :fetch_user


  def fetch_user

    # Check if the session[:user_id] is set, and also make sure it
    # contains a valid (current) user ID - if so, we will set
    # an instance variable containing the user object.
    # By setting the variable here in the controller superclass,
    # it will be available to any action of any controller,
    # making it easy to check the login status of a user anywhere.

    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # Delete this session (clear the ID from the session hash)
    # if the ID did not return a valid user
    unless @current_user.present?
      session[:user_id] = nil
    end

  end  # fetch_user

  def check_if_logged_in
    # Show pages can ONLY be seen by logged-in users
    redirect_to login_path unless @current_user.present?
  end

  def check_if_admin
     redirect_to login_path unless @current_user.present? && @current_user.admin?
  end


end # ApplicationController

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail,  only: [:show, :edit, :update, :destroy]

      before_action :check_if_logged_in, except: [:index, :show]

    def index
      @cocktail = Cocktail.all.order("created_at DESC")
    end

    def show
      # puts "==============================="
      #
      # @cocktail.comments.each { |c| p c }
    end

    def new
      @cocktail = Cocktail.new
    end

    def edit

    end

    def update
      if @cocktail.update(cocktail_params)
        redirect_to @cocktail, notice: "Cocktail was successfully updated"
      else
        render :edit, alert: "Your cocktail wasn't successfully updated"
      end
    end

    def create
      # @cocktail = Cocktail.new(cocktail_params)
      # if @cocktail.save
      @cocktail = @current_user.cocktails.create(cocktail_params)
      if @cocktail.persisted?
        redirect_to @cocktail, notice: "You created a cocktail"
      else
        render :new, alert: "Your cocktail wasn't created"
      end
    end

    def destroy
    @cocktail.destroy

    redirect_to cocktails_path, notice: "Cocktails has been deleted"


    end

    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def map
      @cocktails = Cocktail.where.not(latitude: nil, longitude: nil).select(:name, :latitude, :longitude)
    end

    private
    def cocktail_params
      params.require(:cocktail).permit(:name, :image, :creator, :ingredients, :instructions)
    end


  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @comment = @cocktail.comments.create(params[:comment].permit(:name, :body))
    redirect_to cocktail_path(@cocktail)
end

def destroy
  @cocktail = Cocktail.find(params[:cocktail_id])
  @comment = @cocktail.comments.find(params[:id])
  @comment.destroy
  redirect_to cocktail_path(@cocktail)
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def map
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create

    # See if the email address entered actually exists in the 'users' table
    user = User.find_by email: params[:email]

    # Did we find a user, and if we did, is the password correct?
    if user.present? && user.authenticate( params[:password] )
      # successful login

      # Get Rails to create a new key in a special system variable
      # called 'session'; this variable is remembered ACROSS REQUESTS!
      # (This persistent memory across requests is implemented using
      #  browser cookies, which are stored on your harddrives)
      session[:user_id] = user.id

      redirect_to user_path(user.id)  # go to show page (/users/10 or whatever)

    else
      # failed login (wrong credentials)

      flash[:error] = 'Invalid email or password'
      redirect_to login_path  # show the form again
    end


  end # create


  def destroy
    session[:user_id] = nil  # This logs out the user
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Certain pages are visible only to logged-in users:
  before_action :check_if_logged_in, except: [:new, :create]
  #Lock down admin pages

  before_action :check_if_admin, only: [:index]
  def new
    @user = User.new
  end

  def create

    @user = User.create user_params  # strong params

    if @user.persisted?
      # account created successfully
      session[:user_id] = @user.id  # log them in automatically!
      redirect_to user_path(@user.id)
    else
      # there was an error, so show the signup form again
      # BUT - we want the form to be prefilled, so let's
      # not redirect to the login form, but just render
      # the 'new' form template again. This way, the template
      # can see our @user variable from above, and prefill
      # the form



      #Nope because of rendering, instead of redirecting, the flash message will live for Another page reload
      # Let's just use @user.errors in our template directly
      # Set up our flash variable with appropriate errors to
      # show on the template:
      # flash[:errors] = @user.errors.full_messages # ActiveRecord has set these errors

      render :new
    end


  end # create

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
   @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to @user, notice: "Your profile has been updated"
    else
      render :edit, alert: "Your profile wasn't successfully updated"
    end
  end


  def destroy
  end

  private
  def user_params
    params.require(:user).permit( :name, :email, :image, :password, :password_confirmation )
  end

end # UsersController

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cocktails/_form.html.erb
<div id="login">

<h1>Create a New Cocktail</h1>
<%= simple_form_for(@cocktail) do |f|%>



<div class="field">
<div>
<%= f.label :name %>
</div>
<%= f.text_field :name %>
</div>
<div class="field">
<div>
<%= f.label :image, 'Image URL' %>
</div>
<%= f.text_field :image %>
</div>
<div class="field">
<div>
<%= f.label :creator  %>
</div>
<%= f.text_field :creator %>
</div>
<div class="field">
<div>
<%= f.label :ingredients %>
</div>
<%= f.text_field :ingredients %>
</div>
<div class="field">
<div>
<%= f.label :instructions %>
</div>
<%= f.text_field :instructions %>
</div>
<div class="submit">
<%= f.submit %>
</div>
<% end %>

</div>

<br>

app/views/cocktails/edit.html.erb
<%= link_to "All Cocktails", cocktails_path %>

<h1>Edit Cocktail</h1>

<%= render 'cocktails/form' %>

app/views/cocktails/index.html.erb
<br>
<br>
<div class="all_cocktails">
<% @cocktail.each do |cocktail| %>



     <div id="cocktails_inside">
       <div id="cocktail_name_main_page">
      <%= link_to cocktail.name, cocktail %>  <%# cocktail.user.name %><br>
      </div>
      <%= image_tag cocktail.image, alt: @cocktail.name, class: 'cocktail' %><br>
      <% if @current_user.present? && ( @current_user.admin? || cocktail.user == @current_user ) %>
      <%= link_to "Edit", edit_cocktail_path(cocktail)%><br>
      <% end %>
      <% if @current_user.present? && ( @current_user.admin? || cocktail.user == @current_user ) %>
        <%= link_to "Delete", delete_cocktail_path(cocktail), method: :delete, data: {confirm: "Are you sure?"} %><br>
      <% end %>
      </div>





<% end %>
</div>
<br>
<br>
<br>

app/views/cocktails/map.html.erb
<h1>Cocktails Map</h1>
<p>Find me in app/views/cocktails/map.html.erb</p>

<style>



  #map{
    height: 80vh !important;
    width: 80vw !important;
  }
  html, body {
    height: 100vh;
    width: 100vw;

    margin: 0;
    padding: 0;
  }

</style>
<div id="map">

</div>
<script>
      const cocktails = <%= @cocktails.to_json.html_safe %>

      function initMap() {

        // var myLatLng = {lat: -25.363, lng: 131.044};
        var bounds = new google.maps.LatLngBounds();

        var map = new google.maps.Map(document.getElementById('map'), {
          // zoom: 8,
          // center: {lat: cocktails[0].latitude, lng: cocktails[0].longitude}
        });
        for (var i = 0; i < cocktails.length; i++) {
          const cocktail = cocktails[i]
          var marker = new google.maps.Marker({
            position: {lat: cocktail.latitude, lng: cocktail.longitude},
            map: map,
            title: cocktail.name
          });
          //add the latest marker to the bounding box
        bounds.extend(marker.position)
      } //for
     map.fitBounds( bounds )//make the map fit within the box containing
    }//initMap
</script>
<div id="map_map">

<script async defer

src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDnrWs3SRGJ-lJ6tb4NTAj1118mGtjPcWQ&callback=initMap">
</script>
</div>

<br>
<br>
<br>
<br>
<br>
<br>

app/views/cocktails/new.html.erb
<%= render 'cocktails/form' %>

app/views/cocktails/show.html.erb
<div id="cocktail_title">
  <%= @cocktail.name %>
</div>


<div class="cocktail_details">
 <div>
  <div class="image">
    <% if @cocktail.image.present?  %>
    <%= image_tag @cocktail.image, alt: @cocktail.name, class: 'cocktail_inside' %>
    <% end  %>
  </div>

  <div class="instructions">
    <h3>
    Creator: <%= @cocktail.creator %>
    </h3>

    <br>
    <br>
    <h3>
    Ingredients: <%= @cocktail.ingredients %>
    </h3>

    <br>
    <br>
    <h3>
    Instructions: <%= @cocktail.instructions %>
    </h3>
  </div>

</div>

<div id="cocktail_comments">
<div id="comments">
  <h1>Comments</h1>
  <br>
  <br>
  <%= render @cocktail.comments %>
</div>
  <%= render "comments/form" %>
</div>
</div>

app/views/cocktails/show_MESS.html.erb
<div class="comments_themselves">
<%# <%= @cocktail.comments.count %>
<%= render @cocktail.comments %>
<br>
</div>
<div class="comments_main">
<%= render "comments/form" %>
</div>

<div class="main_content">
<br><br>

        <div id="cocktail_title">
        <p>
             <%= @cocktail.name %>
        </p>
        </div>
        <div>
        <% if @cocktail.image.present?  %>
        <%= image_tag @cocktail.image, alt: @cocktail.name, class: 'cocktail_inside' %>
        <% end  %>
        </div>

  <br>
       <div class="cre_ing_ins">
         <ul>
         <li>
         Creator: <%= @cocktail.creator %>
         </li>
         <br>
         <li >
         Ingredients: <%= @cocktail.ingredients %>
         </li>
         <br>
         <li>
         Instructions: <%= @cocktail.instructions %>
         </li>
         </ul>
       </div>


</div>

app/views/comments/_comment.html.erb
<div class="commented_by_user">


<h3>Name:  <%= comment.name %></h3>
<br>
<h3>Comment:  <%= comment.body %></h3><br>
<p><%= time_ago_in_words(comment.created_at) %></p>
<p><%= link_to 'Delete',[comment.cocktail,comment], method: :delete, data: {confirm: 'Are you sure?'}  %></p>
<br>
</div>

app/views/comments/_form.html.erb
<div class="comment_form">
 <h4>Add Comments: </h4>
  <%= form_for([@cocktail, @cocktail.comments.new]) do |f|%>

  <div class="field">
      <div>
         <%= f.label :name, 'Your Name' %>
      </div>
      <%= f.text_field :name %>
  </div>

  <div class="field">
    <div>
      <%= f.label :body, 'Comment' %>
    </div>
    <%= f.text_field :body %>
  </div>

    <br>

    <div class="submit_comment">
        <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Cocktails</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%# stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

  <div id="main">


<!--
    <div id="logo_text">
    </div> -->



    <div id="menubar">

       <ul id="menu">

         <li><%= link_to "Cocktails", cocktails_path %></li>

          <% if @current_user.present? %>
            You are logged in as: <%= @current_user.name %>
            <% if @current_user.admin %>
            (Admin)
            <% end %>
            <li><%= link_to "Create a new Cocktail", new_cocktail_path %></li>
            |
            <li><%= link_to "Profile", user_path(@current_user.id) %></li>
            |
            <li><%= link_to 'Logout', login_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li>
            |
            <li><%= link_to 'Sign Up', new_user_path %></li>
          <% end %>

        </ul><!-- menu -->

      </div><!-- menubar -->




              <%= yield %>









    <footer>
         <div id="footer">
            Copyright &copy; Hasan Aliyev 2020
          <a href="https://www.facebook.com/TheCocktailPortal/" target="_blank" class="fa fa-facebook" ></a>
          <a href="https://twitter.com/createcocktails?lang=en" target="_blank" class="fa fa-twitter"></a>
          <a href="https://www.youtube.com/channel/UCu9ArHUJZadlhwt3Jt0tqgA" target="_blank" class="fa fa-youtube"></a>
          <a href="https://www.instagram.com/bartendersportal/" target="_blank" class="fa fa-instagram"></a>
         </div>
    </footer>


  </div><!-- main -->
</body>
</html>

app/views/pages/map.html.erb
<h1>Pages#map</h1>
<p>Find me in app/views/pages/map.html.erb</p>

app/views/session/new.html.erb
<br>
<div>
<div id="login">


    <h2>Login</h2>
    <br>
    <div>
      <% if flash[:error] %>
      <!-- Print out any error message for the user -->
        <br>
        <strong><%= flash[:error] %></strong>
        <br>

      <% end %>



        <%= form_tag login_path do %>

          <div class="field">
          <div>
            <%= label_tag :email, 'Email'%>
          </div>

          <%= email_field_tag :email %>
          </div>

          <div class="field">
          <div>
          <%= label_tag :password, 'Password' %>
          </div>
          <%= password_field_tag :password %>
          </div>

        <div class="submit">
          <%= submit_tag 'Login' %>
        </div>
        <% end %>




</div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/users/edit.html.erb
<div class="main_content">
  <div id="login">


<h2>Edit Profile</h2>

<!-- could also just use @user.errors.full_messages here -->
<% if @user.errors.any? %>
    <p>Please correct the following errors:</p>
     <ul>
        <% @user.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
    </ul>
<% end %>

  <%= form_for @user do |f| %>
  <div class="field">
    <div>
    <%= f.label :name %>
    </div>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <div>
    <%= f.label :email %>
    </div>
    <%= f.email_field :email %>

  </div>
  <div class="field">
    <div>
    <%= f.label :image %>
    </div>
    <%= f.text_field :image %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password %>
      </div>
    <%= f.password_field :password %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password_confirmation %>
    </div>
    <%= f.password_field :password_confirmation %>

  </div>
  <div class="submit">
  <%= f.submit 'Update' %>
  </div>
<% end %>























</div>
</div>

<br>

app/views/users/index.html.erb
<h2>All Users</h2>


 <% @users.each do |user| %>

 <%= user.name %>

<% end %>

app/views/users/new.html.erb
<div class="main_content">
  <div id="login">


<h2>Create a New Account</h2>
<br>
<!-- could also just use @user.errors.full_messages here -->
<% if @user.errors.any? %>
    <p>Please correct the following errors:</p>
     <ul>
        <% @user.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
    </ul>
<% end %>

  <%= form_for @user do |f| %>
  <div class="field">
    <div>
    <%= f.label :name %>
    </div>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <div>
    <%= f.label :email %>
    </div>
    <%= f.email_field :email %>

  </div>
  <div class="field">
    <div>
    <%= f.label :image %>
    </div>
    <%= f.text_field :image %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password %>
      </div>
    <%= f.password_field :password %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password_confirmation %>
    </div>
    <%= f.password_field :password_confirmation %>

  </div>
  <div class="submit">
  <%= f.submit 'Sign up' %>
  </div>


</div>

</div>


<br>





<% end %>

app/views/users/show.html.erb
<div id="profile_page">
<h2>Profile<%# @user.name %></h2>
</div>
<div id="edit_profile">
<h4><%= link_to "Edit Profile", edit_user_path %></h4>
</div>


 <% if @user.image.present? %>
  <%= image_tag @user.image, alt: @user.name, class: 'cocktail' %>
 <% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>